<a href="https://colab.research.google.com/github/Miranita-ar/Skripsi-Gojek-App-Review/blob/main/Code/(XF)_Skripsi%20IndoBERT_(Final_XAI_Visualization_Reporting).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ==============================================================
# FINAL XAI VISUALIZATION & REPORTING
# ==============================================================

Analisis Sentimen Ulasan Aplikasi Gojek

Menggunakan Model IndoBERT Base P2

==============================================================

Peneliti

**Miranita Anisa Rohmah**

NIM : 11220940000055

Program Studi : Matematika

Fakultas : Fakultas Sains dan Teknologi

Universitas : UIN Syarif Hidayatullah Jakarta

--------------------------------------------------------------

Notebook

**XF — Final XAI Visualization & Reporting**

--------------------------------------------------------------

## Tujuan Notebook

Notebook ini merupakan tahap akhir dari keseluruhan pipeline Explainable Artificial Intelligence (XAI).

Notebook memanfaatkan seluruh hasil analisis yang telah dihasilkan pada Notebook XE sehingga tidak lagi melakukan proses inferensi maupun perhitungan SHAP dan LIME.

Output notebook meliputi:

- Representative SHAP Dashboard
- Representative LIME Dashboard
- Representative SHAP PNG
- Representative LIME PNG
- Perbandingan SHAP dan LIME
- Visualisasi siap digunakan pada Bab IV
- Ringkasan hasil penelitian
1. Menampilkan dashboard SHAP.
2. Menampilkan dashboard LIME.
3. Menyusun representative sample.
4. Membandingkan SHAP dan LIME.
5. Menghasilkan visualisasi final untuk Bab IV.
6. Menghasilkan dashboard HTML interaktif.
==============================================================

# BAB I Persiapan Lingkungan Analisis

Tahap ini bertujuan untuk menginisialisasi seluruh library, fungsi utilitas, konfigurasi path, serta dataset yang akan digunakan selama proses visualisasi hasil Explainable AI.

## 1.1 Import Library

In [ ]:
# =====================================================
# CELL 1 : IMPORT LIBRARY
# =====================================================

import os
import json
import shutil
import warnings

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

from pathlib import Path

from IPython.display import HTML
from IPython.display import display

warnings.filterwarnings("ignore")

plt.rcParams["figure.dpi"] = 150
plt.rcParams["savefig.dpi"] = 300

print("="*60)
print("IMPORT LIBRARY")
print("="*60)
print()
print("✅ Library berhasil diimport.")

============================================================
IMPORT LIBRARY
============================================================

✅ Library berhasil diimport.

## 1.2 Mount Google Drive

In [ ]:
# =====================================================
# CELL 2 : MOUNT GOOGLE DRIVE
# =====================================================

from google.colab import drive

drive.mount("/content/drive")

print("="*60)
print("MOUNT GOOGLE DRIVE")
print("="*60)
print()
print("✅ Google Drive berhasil di-mount.")

Mounted at /content/drive
============================================================
MOUNT GOOGLE DRIVE
============================================================

✅ Google Drive berhasil di-mount.

## 1.3 Inisialisasi Helper Function

In [ ]:
# =====================================================
# CELL 3 : INITIALIZE HELPER FUNCTION
# =====================================================

def print_header(title):

    print()
    print("="*60)
    print(title)
    print("="*60)


def print_success(message):

    print()
    print(f"✅ {message}")


def print_info(message):

    print(f"ℹ️ {message}")


print("="*60)
print("INITIALIZE HELPER FUNCTION")
print("="*60)
print()
print("✅ Helper Function berhasil diinisialisasi.")

============================================================
INITIALIZE HELPER FUNCTION
============================================================

✅ Helper Function berhasil diinisialisasi.

## 1.4 Konfigurasi Path

In [ ]:
# =====================================================
# CELL 4 : KONFIGURASI PATH
# =====================================================

PATHS = {

    "PROJECT":
    "/content/drive/MyDrive/Skripsi_IndoBERT",

    "XAI":
    "/content/drive/MyDrive/Skripsi_IndoBERT/xai",

    "XE":
    "/content/drive/MyDrive/Skripsi_IndoBERT/xai/XE_Analisis_Hasil_XAI",

    "SHAP":
    "/content/drive/MyDrive/Skripsi_IndoBERT/xai/XE_Analisis_Hasil_XAI/XE_SHAP",

    "LIME":
    "/content/drive/MyDrive/Skripsi_IndoBERT/xai/XE_Analisis_Hasil_XAI/XE_LIME",

    "SUMMARY":
    "/content/drive/MyDrive/Skripsi_IndoBERT/xai/XE_Analisis_Hasil_XAI/Summary"

}

print_header("KONFIGURASI PATH")

print()

for key, value in PATHS.items():

    print_info(f"{key:<10}: {value}")

print()

print_success("Seluruh path berhasil dikonfigurasi.")

============================================================
KONFIGURASI PATH
============================================================

ℹ️ PROJECT   : /content/drive/MyDrive/Skripsi_IndoBERT
ℹ️ XAI       : /content/drive/MyDrive/Skripsi_IndoBERT/xai
ℹ️ XE        : /content/drive/MyDrive/Skripsi_IndoBERT/xai/XE_Analisis_Hasil_XAI
ℹ️ SHAP      : /content/drive/MyDrive/Skripsi_IndoBERT/xai/XE_Analisis_Hasil_XAI/XE_SHAP
ℹ️ LIME      : /content/drive/MyDrive/Skripsi_IndoBERT/xai/XE_Analisis_Hasil_XAI/XE_LIME
ℹ️ SUMMARY   : /content/drive/MyDrive/Skripsi_IndoBERT/xai/XE_Analisis_Hasil_XAI/Summary


✅ Seluruh path berhasil dikonfigurasi.

## 1.5 Load Representative Sample

In [ ]:
# =====================================================
# CELL 5 : LOAD REPRESENTATIVE SAMPLE
# =====================================================

print_header("LOAD REPRESENTATIVE SAMPLE")

SUMMARY_DIR = os.path.join(

    PATHS["XE"],

    "Summary"

)

REPRESENTATIVE_FILE = os.path.join(

    SUMMARY_DIR,

    "Representative_Sample.csv"

)

representative_df = pd.read_csv(

    REPRESENTATIVE_FILE

)

print()

print_info(

    f"Jumlah Representative : {len(representative_df)}"

)

print()

display(

    representative_df.head(6)

)

print()

print_success(

    "Representative Sample berhasil dimuat."

)

============================================================
LOAD REPRESENTATIVE SAMPLE
============================================================

ℹ️ Jumlah Representative : 6

,analysis_order,sample_id,text,actual_label,actual_sentiment,predicted_label,predicted_sentiment,prob_negatif,prob_netral,prob_positif,confidence,correct,prediction_case,confidence_level,selection_reason,sample_group,explain_status,analysis_group,detail_group
0,1,XAI_001,sangat membantu dan mudah,2,Positif,2,Positif,0.000885,0.000943,0.998172,0.998172,True,Benar_Positif,Tinggi,Prediksi benar kelas Positif,High Confidence,Pending,High Confidence,Positif
1,11,XAI_011,kenapa pas butuh banget di kasih driver rada j...,1,Netral,1,Netral,0.075137,0.784807,0.140055,0.784807,True,Benar_Netral,Sedang,Prediksi benar kelas Netral,High Confidence,Pending,High Confidence,Netral
2,6,XAI_006,buruk,0,Negatif,0,Negatif,0.991859,0.004897,0.003244,0.991859,True,Benar_Negatif,Tinggi,Prediksi benar kelas Negatif,High Confidence,Pending,High Confidence,Negatif
3,26,XAI_026,pembayaran gojek wajib 100 pakai gopay donk ja...,2,Positif,2,Positif,0.322563,0.292172,0.385265,0.385265,True,Benar_Confidence_Rendah,Rendah,Prediksi benar dengan confidence rendah,Low Confidence,Pending,Low Confidence,Low Confidence
4,16,XAI_016,oke,1,Netral,2,Positif,0.000980,0.000948,0.998072,0.998072,False,Salah_Netral_ke_Positif,Tinggi,Prediksi salah: Netral menjadi Positif,Error Analysis,Pending,Error Analysis,Netral menjadi Positif
5,21,XAI_021,aplikasi ra jelas blas gak ada notif tiba hila...,1,Netral,0,Negatif,0.984055,0.009309,0.006636,0.984055,False,Salah_Netral_ke_Negatif,Tinggi,Prediksi salah: Netral menjadi Negatif,Error Analysis,Pending,Error Analysis,Netral menjadi Negatif

✅ Representative Sample berhasil dimuat.

## 1.6 Validasi Representative Sample

In [ ]:
# =====================================================
# CELL 6 : VALIDATE REPRESENTATIVE SAMPLE
# =====================================================

print_header("VALIDATE REPRESENTATIVE SAMPLE")

required_columns = [

    "sample_id",

    "analysis_group",

    "detail_group",

    "predicted_sentiment",

    "confidence"

]

missing_columns = [

    col

    for col in required_columns

    if col not in representative_df.columns

]

if len(missing_columns) == 0:

    print()

    print_info(
        "Seluruh kolom Representative Sample tersedia."
    )

else:

    raise ValueError(

        f"Kolom tidak ditemukan : {missing_columns}"

    )

print()

print_success(
    "Representative Sample berhasil divalidasi."
)

============================================================
VALIDATE REPRESENTATIVE SAMPLE
============================================================

ℹ️ Seluruh kolom Representative Sample tersedia.


✅ Representative Sample berhasil divalidasi.

## 1.7 rapikan Struktur Folder

In [ ]:
# =====================================================
# CELL 7 : BUILD SUMMARY DIRECTORY
# =====================================================

print_header("BUILD SUMMARY DIRECTORY")

SUMMARY_DIR = os.path.join(

    PATHS["XE"],

    "Summary"

)

os.makedirs(

    SUMMARY_DIR,

    exist_ok=True

)

print()

print_info(SUMMARY_DIR)

print()

print_success(

    "Folder Summary berhasil dibuat."

)

============================================================
BUILD SUMMARY DIRECTORY
============================================================

ℹ️ /content/drive/MyDrive/Skripsi_IndoBERT/xai/XE_Analisis_Hasil_XAI/Summary


✅ Folder Summary berhasil dibuat.

## 1.8 Migrasi Representative File

In [ ]:
# =====================================================
# CELL 8 : MIGRATE REPRESENTATIVE FILE
# =====================================================

print_header("MIGRATE REPRESENTATIVE FILE")

import shutil

files = [

    "Representative_Sample.csv",

    "Representative_Summary.xlsx"

]

for file_name in files:

    source = os.path.join(

        PATHS["XE"],

        file_name

    )

    destination = os.path.join(

        SUMMARY_DIR,

        file_name

    )

    if os.path.exists(source):

        shutil.move(

            source,

            destination

        )

        print_success(

            f"{file_name} dipindahkan."

        )

    else:

        print_info(

            f"{file_name} sudah berada di Summary."

        )

print()

print_success(

    "Migrasi Summary selesai."

)

============================================================
MIGRATE REPRESENTATIVE FILE
============================================================
ℹ️ Representative_Sample.csv sudah berada di Summary.
ℹ️ Representative_Summary.xlsx sudah berada di Summary.


✅ Migrasi Summary selesai.

## 1.9 Validasi Struktur Folder

In [ ]:
# =====================================================
# CELL 9 : VALIDATE SUMMARY DIRECTORY
# =====================================================

print_header("VALIDATE SUMMARY DIRECTORY")

for file_name in sorted(

    os.listdir(SUMMARY_DIR)

):

    print_info(file_name)

print()

print_success(

    "Folder Summary berhasil divalidasi."

)

============================================================
VALIDATE SUMMARY DIRECTORY
============================================================
ℹ️ Representative_Sample.csv
ℹ️ Representative_Summary.xlsx


✅ Folder Summary berhasil divalidasi.

# BAB II Dashboard SHAP (ARSIP)

Bab ini digunakan untuk mengumpulkan dan menyajikan seluruh hasil Explainable Artificial Intelligence menggunakan metode SHAP yang telah dihasilkan pada notebook sebelumnya.

In [ ]:
# =====================================================
# CELL 10 : INITIALIZE SHAP DASHBOARD
# =====================================================

print_header("INITIALIZE SHAP DASHBOARD")

SHAP_DIR = os.path.join(
    PATHS["XE"],
    "XE_SHAP"
)

SHAP_HTML_DIR = os.path.join(
    SHAP_DIR,
    "HTML"
)

SHAP_PNG_DIR = os.path.join(
    SHAP_DIR,
    "PNG"
)

print()

print_info(f"SHAP      : {SHAP_DIR}")
print_info(f"HTML      : {SHAP_HTML_DIR}")
print_info(f"PNG       : {SHAP_PNG_DIR}")

print()

print_success(
    "Dashboard SHAP berhasil diinisialisasi."
)

============================================================
INITIALIZE SHAP DASHBOARD
============================================================

ℹ️ SHAP      : /content/drive/MyDrive/Skripsi_IndoBERT/xai/XE_Analisis_Hasil_XAI/XE_SHAP
ℹ️ HTML      : /content/drive/MyDrive/Skripsi_IndoBERT/xai/XE_Analisis_Hasil_XAI/XE_SHAP/HTML
ℹ️ PNG       : /content/drive/MyDrive/Skripsi_IndoBERT/xai/XE_Analisis_Hasil_XAI/XE_SHAP/PNG


✅ Dashboard SHAP berhasil diinisialisasi.

## 2.2 Validasi Hasil SHAP

In [ ]:
# =====================================================
# CELL 11 : VALIDATE SHAP RESULT
# =====================================================

print_header("VALIDATE SHAP RESULT")

html_files = []

if os.path.exists(SHAP_HTML_DIR):

    html_files = sorted(

        [
            file
            for file in os.listdir(SHAP_HTML_DIR)
            if file.endswith(".html")
        ]

    )

print()

print_info(
    f"Jumlah HTML SHAP : {len(html_files)}"
)

print()

for file in html_files[:10]:

    print_info(file)

if len(html_files) > 10:

    print_info("...")

print()

print_success(
    "Hasil SHAP berhasil divalidasi."
)

============================================================
VALIDATE SHAP RESULT
============================================================

ℹ️ Jumlah HTML SHAP : 30

ℹ️ XAI_001.html
ℹ️ XAI_002.html
ℹ️ XAI_003.html
ℹ️ XAI_004.html
ℹ️ XAI_005.html
ℹ️ XAI_006.html
ℹ️ XAI_007.html
ℹ️ XAI_008.html
ℹ️ XAI_009.html
ℹ️ XAI_010.html
ℹ️ ...


✅ Hasil SHAP berhasil divalidasi.

## 2.3 Memuat Representative SHAP

In [ ]:
# =====================================================
# CELL 12 : LOAD REPRESENTATIVE SHAP
# =====================================================

print_header("LOAD REPRESENTATIVE SHAP")

shap_representative = representative_df.copy()

print()

print_info(
    f"Jumlah Representative : {len(shap_representative)}"
)

print()

display(

    shap_representative[[
        "sample_id",
        "analysis_group",
        "detail_group"
    ]]

)

print()

print_success(
    "Representative SHAP berhasil dimuat."
)

============================================================
LOAD REPRESENTATIVE SHAP
============================================================

ℹ️ Jumlah Representative : 6

  sample_id   analysis_group            detail_group
0   XAI_001  High Confidence                 Positif
1   XAI_011  High Confidence                  Netral
2   XAI_006  High Confidence                 Negatif
3   XAI_026   Low Confidence          Low Confidence
4   XAI_016   Error Analysis  Netral menjadi Positif
5   XAI_021   Error Analysis  Netral menjadi Negatif

✅ Representative SHAP berhasil dimuat.

## 2.4 Ringkasan Representative SHAP

In [ ]:
# =====================================================
# CELL 13 : BUILD SHAP SUMMARY
# =====================================================

print_header("BUILD SHAP SUMMARY")

summary_table = shap_representative[[
    "sample_id",
    "analysis_group",
    "detail_group",
    "actual_sentiment",
    "predicted_sentiment",
    "confidence"
]]

display(summary_table)

print()

print_success(
    "Ringkasan SHAP berhasil dibuat."
)

============================================================
BUILD SHAP SUMMARY
============================================================

,sample_id,analysis_group,detail_group,actual_sentiment,predicted_sentiment,confidence
0,XAI_001,High Confidence,Positif,Positif,Positif,0.998172
1,XAI_011,High Confidence,Netral,Netral,Netral,0.784807
2,XAI_006,High Confidence,Negatif,Negatif,Negatif,0.991859
3,XAI_026,Low Confidence,Low Confidence,Positif,Positif,0.385265
4,XAI_016,Error Analysis,Netral menjadi Positif,Netral,Positif,0.998072
5,XAI_021,Error Analysis,Netral menjadi Negatif,Netral,Negatif,0.984055

✅ Ringkasan SHAP berhasil dibuat.

## 2.5 Membangun Dashboard SHAP Representative

In [ ]:
# =====================================================
# CELL 14 : BUILD SHAP DASHBOARD
# =====================================================

print_header("BUILD SHAP DASHBOARD")

DASHBOARD_DIR = os.path.join(

    PATHS["XE"],

    "Dashboard"

)

os.makedirs(

    DASHBOARD_DIR,

    exist_ok=True

)

dashboard_shap = os.path.join(

    DASHBOARD_DIR,

    "Dashboard_SHAP.html"

)

print()

print_info(DASHBOARD_DIR)

print()

print_success(

    "Folder Dashboard berhasil dibuat."

)

============================================================
BUILD SHAP DASHBOARD
============================================================

ℹ️ /content/drive/MyDrive/Skripsi_IndoBERT/xai/XE_Analisis_Hasil_XAI/Dashboard


✅ Folder Dashboard berhasil dibuat.

## 2.6 Menyusun Navigasi Dashboard SHAP

In [ ]:
# =====================================================
# CELL 15 : BUILD SHAP NAVIGATION
# =====================================================

print_header("BUILD SHAP NAVIGATION")

navigation = ""

for _, row in shap_representative.iterrows():

    sample_id = row["sample_id"]

    group = row["analysis_group"]

    detail = row["detail_group"]

    navigation += f"""

    <li>

        <a href="#{sample_id}">

        <b>{sample_id}</b>

        -

        {group}

        -

        {detail}

        </a>

    </li>

    """

print()

print_info(

    f"Jumlah Navigation : {len(shap_representative)}"

)

print()

print_success(

    "Navigation berhasil dibuat."

)

============================================================
BUILD SHAP NAVIGATION
============================================================

ℹ️ Jumlah Navigation : 6


✅ Navigation berhasil dibuat.

## 2.7 Menyusun Representative Card

In [ ]:
# =====================================================
# CELL 16 : BUILD REPRESENTATIVE CARD
# =====================================================

print_header("BUILD REPRESENTATIVE CARD")

cards = ""

for _, row in shap_representative.iterrows():

    sample_id = row["sample_id"]

    html_file = f"../XE_SHAP/HTML/{sample_id}.html"

    cards += f"""

    <div id="{sample_id}"

    style="margin-top:40px;">

    <h2>{sample_id}</h2>

    <table border="1"

    cellpadding="6"

    cellspacing="0">

    <tr>

        <td><b>Kelompok</b></td>

        <td>{row['analysis_group']}</td>

    </tr>

    <tr>

        <td><b>Kategori</b></td>

        <td>{row['detail_group']}</td>

    </tr>

    <tr>

        <td><b>Aktual</b></td>

        <td>{row['actual_sentiment']}</td>

    </tr>

    <tr>

        <td><b>Prediksi</b></td>

        <td>{row['predicted_sentiment']}</td>

    </tr>

    <tr>

        <td><b>Confidence</b></td>

        <td>{row['confidence']:.4f}</td>

    </tr>

    </table>

    <br>

    <iframe

        src="{html_file}"

        width="100%"

        height="650"

        style="border:1px solid #cccccc;">

    </iframe>

    </div>

    <hr>

    """

print()

print_info(

    f"Jumlah Card : {len(shap_representative)}"

)

print()

print_success(

    "Representative Card berhasil dibuat."

)

============================================================
BUILD REPRESENTATIVE CARD
============================================================

ℹ️ Jumlah Card : 6


✅ Representative Card berhasil dibuat.

## 2.8 Generate Dashboard SHAP

In [ ]:
# =====================================================
# CELL 17 : GENERATE SHAP DASHBOARD
# =====================================================

print_header("GENERATE SHAP DASHBOARD")

html = f"""

<html>

<head>

<meta charset="utf-8">

<title>

Dashboard SHAP

</title>

<style>

body{{

font-family:Arial;

margin:40px;

}}

a{{

text-decoration:none;

}}

li{{

margin-bottom:8px;

}}

</style>

</head>

<body>

<h1>

Dashboard SHAP Representative Sample

</h1>

<h2>

Navigation

</h2>

<ul>

{navigation}

</ul>

{cards}

</body>

</html>

"""

with open(

    dashboard_shap,

    "w",

    encoding="utf-8"

) as f:

    f.write(html)

print()

print_success(

    "Dashboard SHAP berhasil dibuat."

)

============================================================
GENERATE SHAP DASHBOARD
============================================================


✅ Dashboard SHAP berhasil dibuat.

## 2.9 Validasi Dashboard SHAP

In [ ]:
# =====================================================
# CELL 18 : VALIDATE SHAP DASHBOARD
# =====================================================

print_header("VALIDATE SHAP DASHBOARD")

print()

print_info(

    dashboard_shap

)

print()

print_info(

    f"Exist : {os.path.exists(dashboard_shap)}"

)

print()

print_success(

    "Dashboard SHAP berhasil divalidasi."

)

============================================================
VALIDATE SHAP DASHBOARD
============================================================

ℹ️ /content/drive/MyDrive/Skripsi_IndoBERT/xai/XE_Analisis_Hasil_XAI/Dashboard/Dashboard_SHAP.html

ℹ️ Exist : True


✅ Dashboard SHAP berhasil divalidasi.

## 2.10 Membangun Sidebar Dashboard SHAP Berdasarkan Kelompok Analisis

In [ ]:
# =====================================================
# CELL 19 : BUILD GROUPED SHAP SIDEBAR
# =====================================================

print_header("BUILD GROUPED SHAP SIDEBAR")

group_icon = {

    "High Confidence": "🟢",

    "Low Confidence": "🟡",

    "Error Analysis": "🔴"

}

sidebar_items = ""

for group in [

    "High Confidence",

    "Low Confidence",

    "Error Analysis"

]:

    sidebar_items += f"""

    <h3 style="margin-top:25px;">

    {group_icon[group]} {group}

    </h3>

    """

    subset = shap_representative[

        shap_representative["analysis_group"] == group

    ]

    for _, row in subset.iterrows():

        sidebar_items += f"""

        <button

            class="menu-button"

            onclick="loadSample('{row['sample_id']}')">

            <b>{row['sample_id']}</b><br>

            <span style="font-size:12px;">

            {row['detail_group']}

            </span>

        </button>

        """

print()

print_success(

    "Grouped Sidebar berhasil dibuat."

)

============================================================
BUILD GROUPED SHAP SIDEBAR
============================================================


✅ Grouped Sidebar berhasil dibuat.

## 2.11 Membangun Dashboard Interaktif SHAP

In [ ]:
# =====================================================
# CELL 20 : BUILD SHAP JAVASCRIPT
# =====================================================

print_header("BUILD SHAP JAVASCRIPT")

javascript = """

<script>

function loadSample(sample){

    document.getElementById("viewer").src =

    "../XE_SHAP/HTML/" + sample + ".html";

    document.getElementById("title").innerHTML = sample;

}

window.onload = function(){

    loadSample("XAI_001");

}

</script>

"""

print()

print_success(

    "Javascript berhasil dibuat."

)

============================================================
BUILD SHAP JAVASCRIPT
============================================================


✅ Javascript berhasil dibuat.

## 2.12 Membangun Tampilan Dashboard SHAP

In [ ]:
# =====================================================
# CELL 21 : BUILD SHAP CSS
# =====================================================

print_header("BUILD SHAP CSS")

css = """

<style>

body{

margin:0;

font-family:Arial;

background:#F5F5F5;

}

.container{

display:flex;

height:100vh;

}

.sidebar{

width:320px;

background:white;

padding:20px;

overflow-y:auto;

border-right:1px solid #DDDDDD;

}

.viewer{

flex:1;

display:flex;

flex-direction:column;

background:white;

}

.header{

padding:18px;

background:#1565C0;

color:white;

font-size:22px;

font-weight:bold;

}

.menu-button{

width:100%;

padding:10px;

margin-bottom:10px;

border:none;

border-radius:8px;

background:#FAFAFA;

cursor:pointer;

text-align:left;

box-shadow:0 1px 4px rgba(0,0,0,.15);

}

.menu-button:hover{

background:#E3F2FD;

}

iframe{

flex:1;

width:100%;

border:none;

}

</style>

"""

print()

print_success(

    "CSS berhasil dibuat."

)

============================================================
BUILD SHAP CSS
============================================================


✅ CSS berhasil dibuat.

## 2.13 Generate Dashboard SHAP

In [ ]:
# =====================================================
# CELL 22 : GENERATE SHAP DASHBOARD
# =====================================================

print_header("GENERATE SHAP DASHBOARD")

dashboard_html = f"""

<html>

<head>

<meta charset="utf-8">

<title>

Dashboard SHAP

</title>

{css}

</head>

<body>

<div class="container">

<div class="sidebar">

<h2>

Explainable AI Dashboard

</h2>

<hr>

{sidebar_items}

</div>

<div class="viewer">

<div

id="title"

class="header">

Representative Sample

</div>

<iframe

id="viewer">

</iframe>

</div>

</div>

{javascript}

</body>

</html>

"""

dashboard_file = os.path.join(

    DASHBOARD_DIR,

    "Dashboard_SHAP.html"

)

with open(

    dashboard_file,

    "w",

    encoding="utf-8"

) as f:

    f.write(dashboard_html)

print()

print_info(dashboard_file)

print()

print_success(

    "Dashboard SHAP berhasil dibuat."

)

============================================================
GENERATE SHAP DASHBOARD
============================================================

ℹ️ /content/drive/MyDrive/Skripsi_IndoBERT/xai/XE_Analisis_Hasil_XAI/Dashboard/Dashboard_SHAP.html


✅ Dashboard SHAP berhasil dibuat.

## 2.14 Validasi Dashboard SHAP

In [ ]:
# =====================================================
# CELL 23 : VALIDATE SHAP DASHBOARD
# =====================================================

print_header("VALIDATE SHAP DASHBOARD")

print()

print_info(

    f"Exist : {os.path.exists(dashboard_file)}"

)

print()

print_info(

    dashboard_file

)

print()

print_success(

    "Dashboard SHAP berhasil divalidasi."

)

============================================================
VALIDATE SHAP DASHBOARD
============================================================

ℹ️ Exist : True

ℹ️ /content/drive/MyDrive/Skripsi_IndoBERT/xai/XE_Analisis_Hasil_XAI/Dashboard/Dashboard_SHAP.html


✅ Dashboard SHAP berhasil divalidasi.

# BAB III Dashboard LIME (ARSIP)

Bab ini digunakan untuk membangun dashboard interaktif Explainable Artificial Intelligence menggunakan metode Local Interpretable Model-agnostic Explanations (LIME). Dashboard dirancang agar seluruh representative sample dapat ditampilkan secara interaktif dalam satu halaman sehingga memudahkan proses interpretasi model.

## 3.1 Initialize Dashboard LIME

In [ ]:
# =====================================================
# CELL 24 : INITIALIZE LIME DASHBOARD
# =====================================================

print_header("INITIALIZE LIME DASHBOARD")

LIME_DIR = os.path.join(

    PATHS["XE"],

    "XE_LIME"

)

LIME_HTML_DIR = os.path.join(

    LIME_DIR,

    "HTML"

)

LIME_PNG_DIR = os.path.join(

    LIME_DIR,

    "PNG"

)

print()

print_info(f"LIME      : {LIME_DIR}")
print_info(f"HTML      : {LIME_HTML_DIR}")
print_info(f"PNG       : {LIME_PNG_DIR}")

print()

print_success(

    "Dashboard LIME berhasil diinisialisasi."

)

## 3.2 Validate LIME Result

In [ ]:
# =====================================================
# CELL 25 : VALIDATE LIME RESULT
# =====================================================

print_header("VALIDATE LIME RESULT")

html_files = []

if os.path.exists(LIME_HTML_DIR):

    html_files = sorted(

        [

            file

            for file in os.listdir(LIME_HTML_DIR)

            if file.endswith(".html")

        ]

    )

print()

print_info(

    f"Jumlah HTML : {len(html_files)}"

)

print()

for file in html_files[:12]:

    print_info(file)

if len(html_files) > 12:

    print_info("...")

print()

print_success(

    "Hasil LIME berhasil divalidasi."

)

## 3.3 Load Representative LIME

In [ ]:
# =====================================================
# CELL 26 : LOAD REPRESENTATIVE LIME
# =====================================================

print_header("LOAD REPRESENTATIVE LIME")

lime_representative = representative_df.copy()

print()

print_info(

    f"Jumlah Representative : {len(lime_representative)}"

)

print()

display(

    lime_representative[[

        "sample_id",

        "analysis_group",

        "detail_group",

        "predicted_sentiment",

        "confidence"

    ]]

)

print()

print_success(

    "Representative LIME berhasil dimuat."

)

## 3.4 Build LIME Summary

In [ ]:
# =====================================================
# CELL 27 : BUILD LIME SUMMARY
# =====================================================

print_header("BUILD LIME SUMMARY")

display(

    lime_representative[[

        "sample_id",

        "analysis_group",

        "detail_group",

        "actual_sentiment",

        "predicted_sentiment",

        "confidence"

    ]]

)

print()

print_success(

    "Ringkasan LIME berhasil dibuat."

)

## 3.5 Membangun Sidebar Dashboard LIME

In [ ]:
# =====================================================
# CELL 28 : BUILD GROUPED LIME SIDEBAR
# =====================================================

print_header("BUILD GROUPED LIME SIDEBAR")

group_icon = {

    "High Confidence": "🟢",

    "Low Confidence": "🟡",

    "Error Analysis": "🔴"

}

lime_sidebar = ""

for group in [

    "High Confidence",

    "Low Confidence",

    "Error Analysis"

]:

    lime_sidebar += f"""

    <h3 style="margin-top:25px;">

    {group_icon[group]} {group}

    </h3>

    """

    subset = lime_representative[

        lime_representative["analysis_group"] == group

    ]

    for _, row in subset.iterrows():

        lime_sidebar += f"""

        <button

            class="menu-button"

            onclick="loadLime('{row['sample_id']}')">

            <b>{row['sample_id']}</b><br>

            <span style="font-size:12px;">

            {row['detail_group']}

            </span>

        </button>

        """

print()

print_success(

    "Sidebar LIME berhasil dibuat."

)

## 3.6 Menyusun Metadata Representative Sample

In [ ]:
# =====================================================
# CELL 29 : BUILD METADATA JSON
# =====================================================

print_header("BUILD METADATA JSON")

import json

lime_metadata = {}

for _, row in lime_representative.iterrows():

    lime_metadata[row["sample_id"]] = {

        "group": row["analysis_group"],

        "detail": row["detail_group"],

        "actual": row["actual_sentiment"],

        "prediction": row["predicted_sentiment"],

        "confidence": round(

            float(row["confidence"]) * 100,

            2

        )

    }

metadata_json = json.dumps(

    lime_metadata,

    indent=4,

    ensure_ascii=False

)

print()

print_success(

    "Metadata JSON berhasil dibuat."

)

## 3.7 Menyusun Tampilan Dashboard LIME

In [ ]:
# =====================================================
# CELL 30 : BUILD LIME CSS
# =====================================================

print_header("BUILD LIME CSS")

lime_css = """

<style>

body{

margin:0;

font-family:Arial;

background:#F5F5F5;

}

.container{

display:flex;

height:100vh;

}

.sidebar{

width:320px;

background:white;

padding:20px;

overflow:auto;

border-right:1px solid #DDDDDD;

}

.viewer{

flex:1;

display:flex;

flex-direction:column;

background:white;

}

.header{

background:#2E7D32;

color:white;

padding:18px;

font-size:22px;

font-weight:bold;

}

.info{

padding:20px;

border-bottom:1px solid #DDDDDD;

background:#FAFAFA;

}

iframe{

flex:1;

width:100%;

border:none;

}

.menu-button{

width:100%;

margin-bottom:10px;

padding:10px;

border:none;

border-radius:8px;

background:#FAFAFA;

cursor:pointer;

text-align:left;

}

.menu-button:hover{

background:#E8F5E9;

}

</style>

"""

print()

print_success(

    "CSS Dashboard LIME berhasil dibuat."

)

## 3.8 Membangun JavaScript Dashboard LIME

In [ ]:
# =====================================================
# CELL 31 : BUILD LIME JAVASCRIPT
# =====================================================

print_header("BUILD LIME JAVASCRIPT")

javascript_lime = f"""
<script>

const metadata = {metadata_json};

function loadLime(sample){{

    const data = metadata[sample];

    document.getElementById("title").innerHTML =
        "Representative Sample : " + sample;

    document.getElementById("group").innerHTML =
        data.group;

    document.getElementById("detail").innerHTML =
        data.detail;

    document.getElementById("actual").innerHTML =
        data.actual;

    document.getElementById("prediction").innerHTML =
        data.prediction;

    document.getElementById("confidence").innerHTML =
        data.confidence + " %";

    document.getElementById("viewer").src =
        "../XE_LIME/HTML/" + sample + ".html";

}}

window.onload = function(){{

    loadLime("XAI_001");

}}

</script>
"""

print()

print_info(
    f"Panjang Javascript : {len(javascript_lime):,} karakter"
)

print()

print_success(
    "Javascript Dashboard LIME berhasil dibuat."
)

## 3.9 Membangun Panel Metadata Dashboard LIME

In [ ]:
# =====================================================
# CELL 32 : BUILD METADATA PANEL
# =====================================================

print_header("BUILD METADATA PANEL")

metadata_panel = """

<div class="info">

<h3 style="margin-top:0;color:#2E7D32;">

Informasi Prediksi

</h3>

<table style="width:100%;border-collapse:collapse;">

<tr>

<td width="35%"><b>Kelompok</b></td>

<td id="group"></td>

</tr>

<tr>

<td><b>Kategori</b></td>

<td id="detail"></td>

</tr>

<tr>

<td><b>Label Aktual</b></td>

<td id="actual"></td>

</tr>

<tr>

<td><b>Prediksi Model</b></td>

<td id="prediction"></td>

</tr>

<tr>

<td><b>Confidence</b></td>

<td id="confidence"></td>

</tr>

</table>

</div>

"""

print()

print_success(

    "Panel Metadata berhasil dibuat."

)

## 3.10 Membangun Panel Prediction Probability

In [ ]:
# =====================================================
# CELL 33 : BUILD PROBABILITY PANEL
# =====================================================

print_header("BUILD PROBABILITY PANEL")

probability_panel = """

<div class="info">

<h3 style="margin-top:0;color:#1565C0;">

Prediction Probability

</h3>

<table style="width:100%;">

<tr>

<td width="28%">

Negatif

</td>

<td>

<div style="background:#EEEEEE;height:20px;border-radius:6px;">

<div id="prob_neg"

style="background:#E53935;height:20px;width:0%;
border-radius:6px;">

</div>

</div>

</td>

<td id="neg_value"
width="70px"
style="text-align:right;">

0 %

</td>

</tr>

<tr>

<td>

Netral

</td>

<td>

<div style="background:#EEEEEE;height:20px;border-radius:6px;">

<div id="prob_net"

style="background:#FB8C00;height:20px;width:0%;
border-radius:6px;">

</div>

</div>

</td>

<td id="net_value"

style="text-align:right;">

0 %

</td>

</tr>

<tr>

<td>

Positif

</td>

<td>

<div style="background:#EEEEEE;height:20px;border-radius:6px;">

<div id="prob_pos"

style="background:#43A047;height:20px;width:0%;
border-radius:6px;">

</div>

</div>

</td>

<td id="pos_value"

style="text-align:right;">

0 %

</td>

</tr>

</table>

</div>

"""

print()

print_success(

    "Panel Prediction Probability berhasil dibuat."

)

## 3.11 Menambahkan Probability pada Dashboard

In [ ]:
# =====================================================
# CELL 34 : UPDATE JAVASCRIPT
# =====================================================

print_header("UPDATE LIME JAVASCRIPT")

insert_probability = """

    if(data.probability){

        document.getElementById("prob_neg").style.width =
            data.probability.negatif + "%";

        document.getElementById("prob_net").style.width =
            data.probability.netral + "%";

        document.getElementById("prob_pos").style.width =
            data.probability.positif + "%";

        document.getElementById("neg_value").innerHTML =
            data.probability.negatif + "%";

        document.getElementById("net_value").innerHTML =
            data.probability.netral + "%";

        document.getElementById("pos_value").innerHTML =
            data.probability.positif + "%";

    }

"""

javascript_lime = javascript_lime.replace(

    'document.getElementById("viewer").src =',

    insert_probability + '\n\n    document.getElementById("viewer").src ='

)

print()

print_success(

    "Javascript berhasil diperbarui."

)

## 3.12 Memperbarui Metadata JSON

In [ ]:
# =====================================================
# CELL 35 : UPDATE METADATA JSON
# =====================================================

print_header("UPDATE METADATA JSON")

for sample in lime_metadata:

    lime_metadata[sample]["probability"] = {

        "negatif":0,

        "netral":0,

        "positif":0

    }

metadata_json = json.dumps(

    lime_metadata,

    indent=4,

    ensure_ascii=False

)

print()

print_success(

    "Metadata JSON berhasil diperbarui."

)

## 3.13 Menyiapkan Dashboard Viewer

mau dihapus celll 35-39

In [ ]:
# =====================================================
# CELL 35 : BUILD LIME DASHBOARD DATA
# =====================================================

print_header("BUILD LIME DASHBOARD DATA")

dashboard_data = {}

for _, row in lime_representative.iterrows():

    sample_id = row["sample_id"]

    dashboard_data[sample_id] = {

        "metadata":{

            "group":row["analysis_group"],

            "detail":row["detail_group"],

            "actual":row["actual_sentiment"],

            "prediction":row["predicted_sentiment"],

            "confidence":round(

                float(row["confidence"])*100,

                2

            )

        },

        "classes":{

            "Negatif":None,

            "Netral":None,

            "Positif":None

        }

    }

print()

print_info(

    f"Representative Sample : {len(dashboard_data)}"

)

print()

print_success(

    "Dashboard Data berhasil dibuat."

)

## 3.14 Membaca HTML LIME

In [ ]:
# =====================================================
# CELL 36 : LOAD LIME HTML
# =====================================================

print_header("LOAD LIME HTML")

LIME_HTML_DIR = os.path.join(

    PATHS["XE"],

    "XE_LIME",

    "HTML"

)

loaded_html = 0

for sample in dashboard_data:

    for sentiment in [

        "Negatif",

        "Netral",

        "Positif"

    ]:

        html_file = os.path.join(

            LIME_HTML_DIR,

            f"{sample}_{sentiment}.html"

        )

        if os.path.exists(html_file):

            with open(

                html_file,

                "r",

                encoding="utf-8"

            ) as f:

                dashboard_data[sample]["classes"][sentiment] = f.read()

            loaded_html += 1

print()

print_info(

    f"HTML berhasil dimuat : {loaded_html}"

)

print()

print_success(

    "Seluruh HTML LIME berhasil dimuat."

)

## 3.15 Validasi HTML LIME

In [ ]:
# =====================================================
# CELL 37 : VALIDATE LIME HTML
# =====================================================

print_header("VALIDATE LIME HTML")

print()

for sample in dashboard_data:

    count = 0

    for sentiment in [

        "Negatif",

        "Netral",

        "Positif"

    ]:

        if dashboard_data[sample]["classes"][sentiment] is not None:

            count += 1

    print_info(

        f"{sample} : {count} HTML"

    )

print()

print_success(

    "Seluruh HTML berhasil divalidasi."

)

## 3.16 Menyiapkan JSON Dashboard

In [ ]:
# =====================================================
# CELL 38 : BUILD DASHBOARD JSON
# =====================================================

print_header("BUILD DASHBOARD JSON")

import json

dashboard_json = json.dumps(

    dashboard_data,

    ensure_ascii=False

)

print()

print_info(

    f"Ukuran JSON : {len(dashboard_json):,} karakter"

)

print()

print_success(

    "Dashboard JSON berhasil dibuat."

)

## 3.17 Preview Dashboard

In [ ]:
# =====================================================
# CELL 39 : PREVIEW DASHBOARD
# =====================================================

print_header("PREVIEW DASHBOARD")

from IPython.display import IFrame

IFrame(

    dashboard_lime,

    width=1400,

    height=900

)

# BAB 4

# Dashboard Final XAI

Bab ini membangun dashboard final yang mengintegrasikan seluruh hasil Explainable Artificial Intelligence (XAI), yaitu SHAP dan LIME, berdasarkan enam sampel representatif yang telah dipilih pada notebook XE. Seluruh data yang digunakan pada dashboard dibaca langsung dari hasil keluaran notebook XE tanpa melakukan proses inferensi maupun perhitungan ulang sehingga dashboard hanya berfungsi sebagai media visualisasi dan interpretasi hasil penelitian.

## 4.1 Memuat Seluruh Output Notebook XE

Tahap ini memuat seluruh hasil analisis yang dihasilkan notebook XE, meliputi metadata sampel representatif, visualisasi SHAP, visualisasi LIME, serta metadata JSON yang akan digunakan sebagai sumber data utama dashboard.

In [ ]:
# =====================================================
# CELL 10 : LOAD XE OUTPUT
# =====================================================

print_header("LOAD XE OUTPUT")

import json
from IPython.display import HTML

XE_ROOT = PATHS["XE"]

SUMMARY_DIR = os.path.join(

    XE_ROOT,

    "Summary"

)

SHAP_DIR = os.path.join(

    XE_ROOT,

    "XE_SHAP"

)

LIME_DIR = os.path.join(

    XE_ROOT,

    "XE_LIME"

)

LIME_HTML_DIR = os.path.join(

    LIME_DIR,

    "HTML"

)

LIME_JSON_DIR = os.path.join(

    LIME_DIR,

    "JSON"

)

LIME_PNG_DIR = os.path.join(

    LIME_DIR,

    "PNG"

)

print()

print_info(f"Summary : {SUMMARY_DIR}")

print_info(f"SHAP    : {SHAP_DIR}")

print_info(f"LIME    : {LIME_DIR}")

print()

print_success(

    "Seluruh direktori XE berhasil dimuat."

)

============================================================
LOAD XE OUTPUT
============================================================

ℹ️ Summary : /content/drive/MyDrive/Skripsi_IndoBERT/xai/XE_Analisis_Hasil_XAI/Summary
ℹ️ SHAP    : /content/drive/MyDrive/Skripsi_IndoBERT/xai/XE_Analisis_Hasil_XAI/XE_SHAP
ℹ️ LIME    : /content/drive/MyDrive/Skripsi_IndoBERT/xai/XE_Analisis_Hasil_XAI/XE_LIME


✅ Seluruh direktori XE berhasil dimuat.

## 4.2 Memuat Metadata Representative Sample

In [ ]:
# =====================================================
# CELL 11 : LOAD REPRESENTATIVE
# =====================================================

print_header("LOAD REPRESENTATIVE SAMPLE")

REPRESENTATIVE_FILE = os.path.join(

    SUMMARY_DIR,

    "Representative_Sample.csv"

)

representative_df = pd.read_csv(

    REPRESENTATIVE_FILE

)

print()

print_info(

    f"Jumlah Representative : {len(representative_df)}"

)

print()

display(

    representative_df[

        [

            "sample_id",

            "analysis_group",

            "detail_group",

            "actual_sentiment",

            "predicted_sentiment",

            "confidence"

        ]

    ]

)

print()

print_success(

    "Representative Sample berhasil dimuat."

)

============================================================
LOAD REPRESENTATIVE SAMPLE
============================================================

ℹ️ Jumlah Representative : 6

,sample_id,analysis_group,detail_group,actual_sentiment,predicted_sentiment,confidence
0,XAI_001,High Confidence,Positif,Positif,Positif,0.998172
1,XAI_011,High Confidence,Netral,Netral,Netral,0.784807
2,XAI_006,High Confidence,Negatif,Negatif,Negatif,0.991859
3,XAI_026,Low Confidence,Low Confidence,Positif,Positif,0.385265
4,XAI_016,Error Analysis,Netral menjadi Positif,Netral,Positif,0.998072
5,XAI_021,Error Analysis,Netral menjadi Negatif,Netral,Negatif,0.984055

✅ Representative Sample berhasil dimuat.

## 4.3 Validasi Output Notebook XE

In [ ]:
# =====================================================
# CELL 12 : VALIDATE XE OUTPUT
# =====================================================

print_header("VALIDATE XE OUTPUT")

required_dirs = [

    SUMMARY_DIR,

    SHAP_DIR,

    LIME_HTML_DIR,

    LIME_JSON_DIR,

    LIME_PNG_DIR

]

print()

for folder in required_dirs:

    status = "✓" if os.path.exists(folder) else "✗"

    print_info(

        f"{status} {folder}"

    )

print()

assert os.path.exists(REPRESENTATIVE_FILE)

print_success(

    "Seluruh output Notebook XE tersedia."

)

============================================================
VALIDATE XE OUTPUT
============================================================

ℹ️ ✓ /content/drive/MyDrive/Skripsi_IndoBERT/xai/XE_Analisis_Hasil_XAI/Summary
ℹ️ ✓ /content/drive/MyDrive/Skripsi_IndoBERT/xai/XE_Analisis_Hasil_XAI/XE_SHAP
ℹ️ ✓ /content/drive/MyDrive/Skripsi_IndoBERT/xai/XE_Analisis_Hasil_XAI/XE_LIME/HTML
ℹ️ ✓ /content/drive/MyDrive/Skripsi_IndoBERT/xai/XE_Analisis_Hasil_XAI/XE_LIME/JSON
ℹ️ ✓ /content/drive/MyDrive/Skripsi_IndoBERT/xai/XE_Analisis_Hasil_XAI/XE_LIME/PNG


✅ Seluruh output Notebook XE tersedia.

## 4.4 Membangun Objek Dashboard

Tahap ini mengintegrasikan seluruh metadata representatif beserta hasil visualisasi SHAP dan LIME ke dalam satu objek Python yang akan digunakan sebagai sumber data utama dashboard. Dengan pendekatan ini seluruh komponen dashboard menggunakan sumber data yang sama sehingga mempermudah proses pengembangan maupun pemeliharaan dashboard.

In [ ]:
# =====================================================
# CELL 13 : BUILD DASHBOARD DATA
# =====================================================

print_header("BUILD DASHBOARD DATA")

dashboard_data = {}

for _, row in representative_df.iterrows():

    sample_id = row["sample_id"]

    json_file = os.path.join(

        LIME_JSON_DIR,

        f"{sample_id}.json"

    )

    with open(

        json_file,

        "r",

        encoding="utf-8"

    ) as f:

        lime_json = json.load(f)

    dashboard_data[sample_id] = {

        "metadata": row.to_dict(),

        "lime": lime_json

    }

print()

print_info(

    f"Representative Loaded : {len(dashboard_data)}"

)

print()

print_success(

    "Dashboard Data berhasil dibuat."

)

============================================================
BUILD DASHBOARD DATA
============================================================

ℹ️ Representative Loaded : 6


✅ Dashboard Data berhasil dibuat.

## 4.5 Validasi Objek Dashboard

In [ ]:
# =====================================================
# CELL 14 : VALIDATE DASHBOARD DATA
# =====================================================

print_header("VALIDATE DASHBOARD DATA")

print()

for sample_id, value in dashboard_data.items():

    print_info(

        f"{sample_id}"

    )

    print(

        f"   Group      : {value['metadata']['analysis_group']}"

    )

    print(

        f"   Prediction : {value['metadata']['predicted_sentiment']}"

    )

    print(

        f"   Confidence : {value['metadata']['confidence']:.6f}"

    )

print()

print_success(

    "Dashboard Data berhasil divalidasi."

)

============================================================
VALIDATE DASHBOARD DATA
============================================================

ℹ️ XAI_001
   Group      : High Confidence
   Prediction : Positif
   Confidence : 0.998172
ℹ️ XAI_011
   Group      : High Confidence
   Prediction : Netral
   Confidence : 0.784807
ℹ️ XAI_006
   Group      : High Confidence
   Prediction : Negatif
   Confidence : 0.991859
ℹ️ XAI_026
   Group      : Low Confidence
   Prediction : Positif
   Confidence : 0.385265
ℹ️ XAI_016
   Group      : Error Analysis
   Prediction : Positif
   Confidence : 0.998072
ℹ️ XAI_021
   Group      : Error Analysis
   Prediction : Negatif
   Confidence : 0.984055


✅ Dashboard Data berhasil divalidasi.

## 4.6 Membangun Sidebar Dashboard

Tahap ini membangun struktur navigasi dashboard berdasarkan kategori analisis yang terdiri atas High Confidence, Low Confidence, dan Error Analysis. Sidebar digunakan sebagai komponen utama untuk memilih sampel representatif yang akan ditampilkan pada panel visualisasi.

In [ ]:
# =====================================================
# CELL 15 : BUILD SIDEBAR
# =====================================================

print_header("BUILD SIDEBAR")

sidebar_structure = {

    "High Confidence": [],

    "Low Confidence": [],

    "Error Analysis": []

}

for sample_id, data in dashboard_data.items():

    sidebar_structure[

        data["metadata"]["analysis_group"]

    ].append({

        "sample_id": sample_id,

        "title": data["metadata"]["detail_group"]

    })

print()

for group, items in sidebar_structure.items():

    print_info(group)

    for item in items:

        print(

            f"   • {item['sample_id']}"

            f"  ({item['title']})"

        )

    print()

print_success(

    "Sidebar berhasil dibuat."

)

============================================================
BUILD SIDEBAR
============================================================

ℹ️ High Confidence
   • XAI_001  (Positif)
   • XAI_011  (Netral)
   • XAI_006  (Negatif)

ℹ️ Low Confidence
   • XAI_026  (Low Confidence)

ℹ️ Error Analysis
   • XAI_016  (Netral menjadi Positif)
   • XAI_021  (Netral menjadi Negatif)


✅ Sidebar berhasil dibuat.

## 4.7 Validasi Sidebar

In [ ]:
# =====================================================
# CELL 16 : VALIDATE SIDEBAR
# =====================================================

print_header("VALIDATE SIDEBAR")

assert len(sidebar_structure["High Confidence"]) == 3

assert len(sidebar_structure["Low Confidence"]) == 1

assert len(sidebar_structure["Error Analysis"]) == 2

print()

print_info(

    f"High Confidence : "

    f"{len(sidebar_structure['High Confidence'])}"

)

print_info(

    f"Low Confidence : "

    f"{len(sidebar_structure['Low Confidence'])}"

)

print_info(

    f"Error Analysis : "

    f"{len(sidebar_structure['Error Analysis'])}"

)

print()

print_success(

    "Sidebar berhasil divalidasi."

)

============================================================
VALIDATE SIDEBAR
============================================================

ℹ️ High Confidence : 3
ℹ️ Low Confidence : 1
ℹ️ Error Analysis : 2


✅ Sidebar berhasil divalidasi.

## 4.8 Membangun Metadata Panel

Panel metadata digunakan untuk menampilkan informasi utama setiap sampel representatif yang dipilih pengguna melalui sidebar. Informasi tersebut meliputi identitas sampel, kategori analisis, label aktual, hasil prediksi model, tingkat confidence, serta teks ulasan.

In [ ]:
# =====================================================
# CELL 17 : BUILD METADATA PANEL
# =====================================================

print_header("BUILD METADATA PANEL")

metadata_panel = {}

for sample_id, value in dashboard_data.items():

    meta = value["metadata"]

    metadata_panel[sample_id] = {

        "sample_id": sample_id,

        "analysis_group": meta["analysis_group"],

        "detail_group": meta["detail_group"],

        "actual_sentiment": meta["actual_sentiment"],

        "predicted_sentiment": meta["predicted_sentiment"],

        "confidence": float(meta["confidence"]),

        "text": meta["text"]

    }

print()

print_info(

    f"Metadata Panel : {len(metadata_panel)} Sample"

)

print()

print_success(

    "Metadata Panel berhasil dibuat."

)

============================================================
BUILD METADATA PANEL
============================================================

ℹ️ Metadata Panel : 6 Sample


✅ Metadata Panel berhasil dibuat.

## 4.9 Validasi Metadata Panel

In [ ]:
# =====================================================
# CELL 18 : VALIDATE METADATA PANEL
# =====================================================

print_header("VALIDATE METADATA PANEL")

print()

for sample_id, meta in metadata_panel.items():

    print_info(sample_id)

    print(

        f"   Group      : {meta['analysis_group']}"

    )

    print(

        f"   Aktual     : {meta['actual_sentiment']}"

    )

    print(

        f"   Prediksi   : {meta['predicted_sentiment']}"

    )

    print(

        f"   Confidence : {meta['confidence']:.6f}"

    )

    print(

        f"   Text       : {meta['text'][:60]}..."

    )

    print()

print_success(

    "Metadata Panel berhasil divalidasi."

)

============================================================
VALIDATE METADATA PANEL
============================================================

ℹ️ XAI_001
   Group      : High Confidence
   Aktual     : Positif
   Prediksi   : Positif
   Confidence : 0.998172
   Text       : sangat membantu dan mudah...

ℹ️ XAI_011
   Group      : High Confidence
   Aktual     : Netral
   Prediksi   : Netral
   Confidence : 0.784807
   Text       : kenapa pas butuh banget di kasih driver rada jauhan pas sant...

ℹ️ XAI_006
   Group      : High Confidence
   Aktual     : Negatif
   Prediksi   : Negatif
   Confidence : 0.991859
   Text       : buruk...

ℹ️ XAI_026
   Group      : Low Confidence
   Aktual     : Positif
   Prediksi   : Positif
   Confidence : 0.385265
   Text       : pembayaran gojek wajib 100 pakai gopay donk jangan pakai cas...

ℹ️ XAI_016
   Group      : Error Analysis
   Aktual     : Netral
   Prediksi   : Positif
   Confidence : 0.998072
   Text       : oke...

ℹ️ XAI_021
   Group      : Error Analysis
   Aktual     : Netral
   Prediksi   : Negatif
   Confidence : 0.984055
   Text       : aplikasi ra jelas blas gak ada notif tiba hilang semua...


✅ Metadata Panel berhasil divalidasi.

## 4.10 Membangun Asset Panel

Panel ini mengintegrasikan seluruh file visualisasi SHAP dan LIME yang dihasilkan notebook XE. Informasi ini digunakan dashboard untuk menampilkan visualisasi secara dinamis sesuai sampel yang dipilih.

In [ ]:
# =====================================================
# CELL 19 : BUILD ASSET PANEL
# =====================================================

print_header("BUILD ASSET PANEL")

asset_panel = {}

for sample_id, value in dashboard_data.items():

    classes = value["lime"]["classes"]

    asset_panel[sample_id] = classes

print()

print_info(

    f"Asset Panel : {len(asset_panel)} Sample"

)

print()

print_success(

    "Asset Panel berhasil dibuat."

)

============================================================
BUILD ASSET PANEL
============================================================

ℹ️ Asset Panel : 6 Sample


✅ Asset Panel berhasil dibuat.

## 4.11 Validasi Aset Panel

In [ ]:
# =====================================================
# CELL 20 : VALIDATE ASSET PANEL
# =====================================================

print_header("VALIDATE ASSET PANEL")

print()

for sample_id, assets in asset_panel.items():

    print_info(sample_id)

    for cls, files in assets.items():

        print(

            f"   {cls}"

        )

        print(

            f"      HTML : {files['html']}"

        )

        print(

            f"      PNG  : {files['png']}"

        )

    print()

print_success(

    "Asset Panel berhasil divalidasi."

)

============================================================
VALIDATE ASSET PANEL
============================================================

ℹ️ XAI_001
   Negatif
      HTML : HTML/XAI_001_Negatif.html
      PNG  : PNG/XAI_001_Negatif.png
   Netral
      HTML : HTML/XAI_001_Netral.html
      PNG  : PNG/XAI_001_Netral.png
   Positif
      HTML : HTML/XAI_001_Positif.html
      PNG  : PNG/XAI_001_Positif.png

ℹ️ XAI_011
   Negatif
      HTML : HTML/XAI_011_Negatif.html
      PNG  : PNG/XAI_011_Negatif.png
   Netral
      HTML : HTML/XAI_011_Netral.html
      PNG  : PNG/XAI_011_Netral.png
   Positif
      HTML : HTML/XAI_011_Positif.html
      PNG  : PNG/XAI_011_Positif.png

ℹ️ XAI_006
   Negatif
      HTML : HTML/XAI_006_Negatif.html
      PNG  : PNG/XAI_006_Negatif.png
   Netral
      HTML : HTML/XAI_006_Netral.html
      PNG  : PNG/XAI_006_Netral.png
   Positif
      HTML : HTML/XAI_006_Positif.html
      PNG  : PNG/XAI_006_Positif.png

ℹ️ XAI_026
   Negatif
      HTML : HTML/XAI_026_Negatif.html
      PNG  : PNG/XAI_026_Negatif.png
   Netral
      HTML : HTML/XAI_026_Netral.html
      PNG  : PNG/XAI_026_Netral.png
   Positif
      HTML : HTML/XAI_026_Positif.html
      PNG  : PNG/XAI_026_Positif.png

ℹ️ XAI_016
   Negatif
      HTML : HTML/XAI_016_Negatif.html
      PNG  : PNG/XAI_016_Negatif.png
   Netral
      HTML : HTML/XAI_016_Netral.html
      PNG  : PNG/XAI_016_Netral.png
   Positif
      HTML : HTML/XAI_016_Positif.html
      PNG  : PNG/XAI_016_Positif.png

ℹ️ XAI_021
   Negatif
      HTML : HTML/XAI_021_Negatif.html
      PNG  : PNG/XAI_021_Negatif.png
   Netral
      HTML : HTML/XAI_021_Netral.html
      PNG  : PNG/XAI_021_Netral.png
   Positif
      HTML : HTML/XAI_021_Positif.html
      PNG  : PNG/XAI_021_Positif.png


✅ Asset Panel berhasil divalidasi.

## 4.12 Membangun Dashboard Layout

Tahap ini membangun struktur utama dashboard yang terdiri atas sidebar navigasi, panel metadata, panel visualisasi SHAP, dan panel visualisasi LIME. Layout ini menjadi kerangka utama sebelum seluruh komponen diintegrasikan menjadi dashboard interaktif.

In [ ]:
# =====================================================
# CELL 21 : BUILD DASHBOARD LAYOUT
# =====================================================

print_header("BUILD DASHBOARD LAYOUT")

dashboard_layout = {

    "sidebar": sidebar_structure,

    "metadata": metadata_panel,

    "assets": asset_panel

}

print()

print_info(

    f"Sidebar    : {len(dashboard_layout['sidebar'])} Group"

)

print_info(

    f"Metadata   : {len(dashboard_layout['metadata'])} Sample"

)

print_info(

    f"Assets     : {len(dashboard_layout['assets'])} Sample"

)

print()

print_success(

    "Dashboard Layout berhasil dibuat."

)

============================================================
BUILD DASHBOARD LAYOUT
============================================================

ℹ️ Sidebar    : 3 Group
ℹ️ Metadata   : 6 Sample
ℹ️ Assets     : 6 Sample


✅ Dashboard Layout berhasil dibuat.

## 4.13 Validasi Dashboard Layout

In [ ]:
# =====================================================
# CELL 22 : VALIDATE DASHBOARD LAYOUT
# =====================================================

print_header("VALIDATE DASHBOARD LAYOUT")

assert "sidebar" in dashboard_layout
assert "metadata" in dashboard_layout
assert "assets" in dashboard_layout

print()

print_info(

    "Sidebar    ✓"

)

print_info(

    "Metadata   ✓"

)

print_info(

    "Assets     ✓"

)

print()

print_success(

    "Dashboard Layout berhasil divalidasi."

)

============================================================
VALIDATE DASHBOARD LAYOUT
============================================================

ℹ️ Sidebar    ✓
ℹ️ Metadata   ✓
ℹ️ Assets     ✓


✅ Dashboard Layout berhasil divalidasi.

## 4.14 Membangun Sidebar HTML

Tahap ini membangun komponen HTML untuk sidebar dashboard yang berfungsi sebagai navigasi utama dalam memilih sampel representatif berdasarkan kategori analisis.

In [ ]:
# =====================================================
# CELL 23 : BUILD SIDEBAR HTML
# =====================================================

print_header("BUILD SIDEBAR HTML")

sidebar_html = ""

for group, items in sidebar_structure.items():

    sidebar_html += f"""
    <div class="sidebar-group">
        <h3>{group}</h3>
    """

    for item in items:

        sidebar_html += f"""
        <button class="sample-btn"
                data-sample="{item['sample_id']}">
            {item['title']}
        </button>
        """

    sidebar_html += "</div>"

print()

print_info(

    f"Panjang HTML : {len(sidebar_html):,} karakter"

)

print()

print_success(

    "Sidebar HTML berhasil dibuat."

)

============================================================
BUILD SIDEBAR HTML
============================================================

ℹ️ Panjang HTML : 988 karakter


✅ Sidebar HTML berhasil dibuat.

## 4.15 Preview Sidebar

In [ ]:
# =====================================================
# CELL 24 : PREVIEW SIDEBAR
# =====================================================

print_header("PREVIEW SIDEBAR")

sidebar_preview = f"""
<style>

.sidebar{{
width:280px;
padding:20px;
border-right:1px solid #ddd;
font-family:Arial;
}}

.sidebar-group{{
margin-bottom:25px;
}}

.sidebar-group h3{{
font-size:18px;
margin-bottom:10px;
}}

.sample-btn{{
display:block;
width:100%;
margin-bottom:8px;
padding:8px;
text-align:left;
cursor:pointer;
border:1px solid #ddd;
border-radius:6px;
background:white;
}}

.sample-btn:hover{{
background:#f2f2f2;
}}

</style>

<div class="sidebar">

{sidebar_html}

</div>
"""

HTML(sidebar_preview)

============================================================
PREVIEW SIDEBAR
============================================================

## 4.16 Membangun Dashboard Template

Tahap ini membangun kerangka utama dashboard yang terdiri atas sidebar, panel metadata, panel visualisasi SHAP, dan panel visualisasi LIME. Seluruh isi panel akan diperbarui secara dinamis menggunakan JavaScript sesuai sampel yang dipilih pengguna.

In [ ]:
# =====================================================
# CELL 25 : BUILD DASHBOARD TEMPLATE
# =====================================================

print_header("BUILD DASHBOARD TEMPLATE")

dashboard_template = f"""

<style>

body{{
font-family:Arial,sans-serif;
margin:0;
padding:0;
}}

.wrapper{{
display:flex;
height:100vh;
}}

.sidebar{{
width:280px;
border-right:1px solid #ddd;
padding:20px;
overflow:auto;
}}

.content{{
flex:1;
padding:20px;
overflow:auto;
}}

.card{{
background:white;
border:1px solid #ddd;
border-radius:10px;
padding:18px;
margin-bottom:18px;
}}

.card h2{{
margin-top:0;
}}

iframe{{
width:100%;
height:620px;
border:none;
}}

img{{
width:100%;
}}

</style>

<div class="wrapper">

<div class="sidebar">

{sidebar_html}

</div>

<div class="content">

<div class="card">

<h2 id="title">

Representative Sample

</h2>

<div id="metadata">

Silakan pilih sampel.

</div>

</div>

<div class="card">

<h2>

SHAP Explanation

</h2>

<div id="shap_panel">

Belum dipilih.

</div>

</div>

<div class="card">

<h2>

LIME Explanation

</h2>

<div id="lime_panel">

Belum dipilih.

</div>

</div>

</div>

</div>

"""

print()

print_info(

    f"Panjang Template : {len(dashboard_template):,} karakter"

)

print()

print_success(

    "Dashboard Template berhasil dibuat."

)

============================================================
BUILD DASHBOARD TEMPLATE
============================================================

ℹ️ Panjang Template : 1,880 karakter


✅ Dashboard Template berhasil dibuat.

## 4.17 Preview Dashboard Template

In [ ]:
# =====================================================
# CELL 26 : PREVIEW DASHBOARD TEMPLATE
# =====================================================

print_header("PREVIEW DASHBOARD TEMPLATE")

HTML(dashboard_template)

============================================================
PREVIEW DASHBOARD TEMPLATE
============================================================

## 4.18 Membangun Dashboard JSON

Tahap ini menggabungkan seluruh metadata dan aset visualisasi ke dalam satu objek JSON yang akan digunakan sebagai sumber data utama oleh JavaScript pada dashboard interaktif.

In [ ]:
# =====================================================
# CELL 27 : BUILD DASHBOARD JSON
# =====================================================

print_header("BUILD DASHBOARD JSON")

dashboard_json = {}

for sample_id in metadata_panel.keys():

    dashboard_json[sample_id] = {

        "metadata": metadata_panel[sample_id],

        "assets": asset_panel[sample_id]

    }

dashboard_json_text = json.dumps(

    dashboard_json,

    ensure_ascii=False,

    indent=4

)

print()

print_info(

    f"Panjang JSON : {len(dashboard_json_text):,} karakter"

)

print()

print_success(

    "Dashboard JSON berhasil dibuat."

)

============================================================
BUILD DASHBOARD JSON
============================================================

ℹ️ Panjang JSON : 5,112 karakter


✅ Dashboard JSON berhasil dibuat.

## 4.19 Validasi Dashboard JSON

In [ ]:
# =====================================================
# CELL 28 : VALIDATE DASHBOARD JSON
# =====================================================

print_header("VALIDATE DASHBOARD JSON")

print()

print_info(

    f"Jumlah Sample : {len(dashboard_json)}"

)

print()

for sample in dashboard_json:

    print_info(sample)

print()

print_success(

    "Dashboard JSON berhasil divalidasi."

)

============================================================
VALIDATE DASHBOARD JSON
============================================================

ℹ️ Jumlah Sample : 6

ℹ️ XAI_001
ℹ️ XAI_011
ℹ️ XAI_006
ℹ️ XAI_026
ℹ️ XAI_016
ℹ️ XAI_021


✅ Dashboard JSON berhasil divalidasi.

## 4.20 Membangun JavaScript Dashboard

Tahap ini membangun objek JavaScript yang akan menghubungkan data dashboard dengan komponen HTML sehingga setiap perubahan sampel pada sidebar dapat memperbarui isi dashboard secara dinamis.

In [ ]:
# =====================================================
# CELL 29 : BUILD DASHBOARD JAVASCRIPT
# =====================================================

print_header("BUILD DASHBOARD JAVASCRIPT")

dashboard_js = f"""

const dashboardData =

{dashboard_json_text};

"""

print()

print_info(

    f"Panjang Javascript : {len(dashboard_js):,} karakter"

)

print()

print_success(

    "Javascript Dashboard berhasil dibuat."

)

============================================================
BUILD DASHBOARD JAVASCRIPT
============================================================

ℹ️ Panjang Javascript : 5,140 karakter


✅ Javascript Dashboard berhasil dibuat.

## 4.21 Membangun JavaScript Dashboard

In [ ]:
# =====================================================
# CELL 30 : BUILD DASHBOARD SCRIPT
# =====================================================

print_header("BUILD DASHBOARD SCRIPT")

dashboard_script = """
<script>

const dashboardData = __JSON__;

function showSample(sampleId){

    const sample = dashboardData[sampleId];

    if(!sample) return;

    document.getElementById("title").innerHTML =
        sample.metadata.sample_id;

    document.getElementById("metadata").innerHTML = `
        <table style="width:100%;border-collapse:collapse">

        <tr>
            <td><b>Group</b></td>
            <td>${sample.metadata.analysis_group}</td>
        </tr>

        <tr>
            <td><b>Detail</b></td>
            <td>${sample.metadata.detail_group}</td>
        </tr>

        <tr>
            <td><b>Actual</b></td>
            <td>${sample.metadata.actual_sentiment}</td>
        </tr>

        <tr>
            <td><b>Prediction</b></td>
            <td>${sample.metadata.predicted_sentiment}</td>
        </tr>

        <tr>
            <td><b>Confidence</b></td>
            <td>${(sample.metadata.confidence*100).toFixed(2)}%</td>
        </tr>

        <tr>
            <td><b>Text</b></td>
            <td>${sample.metadata.text}</td>
        </tr>

        </table>
    `;

    document.getElementById("shap_panel").innerHTML =
        `<img src="${sample.assets.shap_png}" style="width:100%">`;

    document.getElementById("lime_panel").innerHTML =
        `<iframe src="${sample.assets.lime_html}"
                 style="width:100%;height:650px;border:none;">
         </iframe>`;

}

</script>
"""

dashboard_script = dashboard_script.replace(
    "__JSON__",
    dashboard_json_text
)

print()

print_info(
    f"Panjang Script : {len(dashboard_script):,} karakter"
)

print()

print_success(
    "Dashboard Script berhasil dibuat."
)

============================================================
BUILD DASHBOARD SCRIPT
============================================================

ℹ️ Panjang Script : 6,522 karakter


✅ Dashboard Script berhasil dibuat.

## 4.22 Menambahkan Event Sidebar

In [ ]:
# =====================================================
# CELL 31 : ATTACH SIDEBAR EVENT
# =====================================================

print_header("ATTACH SIDEBAR EVENT")

sidebar_html_event = ""

for group, items in sidebar_structure.items():

    sidebar_html_event += f"""
    <div class="sidebar-group">
        <h3>{group}</h3>
    """

    for item in items:

        sidebar_html_event += f"""
        <button class="sample-btn"
                onclick="showSample('{item['sample_id']}')">
            {item['title']}
        </button>
        """

    sidebar_html_event += "</div>"

print()

print_info(
    "Event onclick berhasil dipasang."
)

print()

print_success(
    "Sidebar siap digunakan."
)

============================================================
ATTACH SIDEBAR EVENT
============================================================

ℹ️ Event onclick berhasil dipasang.


✅ Sidebar siap digunakan.

## 4.23 Membangun Dashboard Final

In [ ]:
# =====================================================
# CELL 32 : BUILD FINAL DASHBOARD
# =====================================================

print_header("BUILD FINAL DASHBOARD")

dashboard_html = dashboard_template.replace(

    sidebar_html,

    sidebar_html_event

)

dashboard_html = dashboard_html + dashboard_script

print()

print_info(

    f"Panjang Dashboard : {len(dashboard_html):,} karakter"

)

print()

print_success(

    "Dashboard Final berhasil dibuat."

)

============================================================
BUILD FINAL DASHBOARD
============================================================

ℹ️ Panjang Dashboard : 8,462 karakter


✅ Dashboard Final berhasil dibuat.

## 4.24 Menampilkan Dashboard

In [ ]:
# =====================================================
# CELL 33 : DISPLAY DASHBOARD
# =====================================================

print_header("DISPLAY DASHBOARD")

display(HTML(dashboard_html))

============================================================
DISPLAY DASHBOARD
============================================================