<a href="https://colab.research.google.com/github/Miranita-ar/Skripsi-Gojek-App-Review/blob/main/Code/(XG)_Skripsi_IndoBERT_(XAI_Analysis).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# BAB 1 Persiapan Analisis XAI

Notebook ini digunakan untuk menganalisis seluruh hasil visualisasi SHAP dan LIME berdasarkan 30 sampel kandidat dari enam kategori analisis. Notebook ini bertujuan membantu proses pemilihan representative sample yang akan dibahas pada Bab 4 skripsi.

## 1.1 Import Library

In [ ]:
# =====================================================
# CELL 1 : IMPORT LIBRARY
# =====================================================

import os
import json
import shutil

import pandas as pd
import numpy as np

from IPython.display import display
from IPython.display import HTML
from IPython.display import Image

print("="*60)
print("IMPORT LIBRARY")
print("="*60)

print()

print("✓ Library berhasil dimuat.")

============================================================
IMPORT LIBRARY
============================================================

✓ Library berhasil dimuat.

## 1.2 Mount Google Drive

Notebook mengakses seluruh output SHAP maupun LIME yang telah dihasilkan pada notebook XC dan XE melalui Google Drive.

In [ ]:
# =====================================================
# CELL 2 : MOUNT GOOGLE DRIVE
# =====================================================

from google.colab import drive

drive.mount("/content/drive")

print("="*60)
print("GOOGLE DRIVE BERHASIL DIHUBUNGKAN")
print("="*60)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
============================================================
GOOGLE DRIVE BERHASIL DIHUBUNGKAN
============================================================

## 1.3 Inisialisasi Helper Function

Beberapa helper function digunakan agar seluruh notebook XA–XG memiliki format output yang konsisten.

In [ ]:
# =====================================================
# CELL 3 : INITIALIZE HELPER FUNCTION
# =====================================================

def print_header(title):
    print()
    print("="*60)
    print(title.upper())
    print("="*60)
    print()

def print_info(msg):
    print(f"ℹ️ {msg}")

def print_success(msg):
    print()
    print(f"✅ {msg}")

## 1.4 Konfigurasi Path

Seluruh direktori yang digunakan pada notebook ini dikonfigurasi pada satu lokasi agar mudah digunakan kembali pada setiap proses analisis.

In [ ]:
# =====================================================
# CELL 4 : CONFIGURE PATH
# =====================================================

print_header("CONFIGURE PATH")

PROJECT_PATH = "/content/drive/MyDrive/Skripsi_IndoBERT"

PATHS = {

    "PROJECT": PROJECT_PATH,

    "XC": os.path.join(
        PROJECT_PATH,
        "xai",
        "XC_SHAP_Analysis"
    ),

    "XE": os.path.join(
        PROJECT_PATH,
        "xai",
        "XE_Analisis_Hasil_XAI"
    ),

    "XG": os.path.join(
        PROJECT_PATH,
        "xai",
        "XG_Analysis"
    )

}

for key, value in PATHS.items():

    print_info(f"{key} : {value}")

print_success(
    "Konfigurasi path berhasil dibuat."
)

============================================================
CONFIGURE PATH
============================================================

ℹ️ PROJECT : /content/drive/MyDrive/Skripsi_IndoBERT
ℹ️ XC : /content/drive/MyDrive/Skripsi_IndoBERT/xai/XC_SHAP_Analysis
ℹ️ XE : /content/drive/MyDrive/Skripsi_IndoBERT/xai/XE_Analisis_Hasil_XAI
ℹ️ XG : /content/drive/MyDrive/Skripsi_IndoBERT/xai/XG_Analysis

✅ Konfigurasi path berhasil dibuat.

## 1.5 Load Summary Local SHAP

Notebook menggunakan file *summary_local_shap.csv* sebagai dataset utama karena file tersebut berisi seluruh 30 sampel kandidat yang digunakan baik pada SHAP maupun LIME.

In [ ]:
# =====================================================
# CELL 5 : LOAD SUMMARY LOCAL SHAP
# =====================================================

print_header("LOAD SUMMARY LOCAL SHAP")

SUMMARY_FILE = os.path.join(

    PATHS["XC"],

    "csv",

    "summary_local_shap.csv"

)

summary_df = pd.read_csv(
    SUMMARY_FILE
)

print_info(
    f"Jumlah Sample : {len(summary_df)}"
)

display(

    summary_df.head()

)

print_success(
    "Summary Local SHAP berhasil dimuat."
)

============================================================
LOAD SUMMARY LOCAL SHAP
============================================================

ℹ️ Jumlah Sample : 30

,sample_id,actual_sentiment,predicted_sentiment,confidence,sample_group,top_token,top_positive_token,top_negative_token,mean_abs_shap,max_abs_shap
0,XAI_001,Positif,Positif,0.998172,High Confidence,mudah,mudah,NaN,2.366605,3.954137
1,XAI_002,Positif,Positif,0.998167,High Confidence,membantu,membantu,NaN,2.014174,4.556612
2,XAI_003,Positif,Positif,0.998162,High Confidence,membantu,membantu,NaN,2.711681,5.207576
3,XAI_004,Positif,Positif,0.998159,High Confidence,membantu,membantu,NaN,2.365625,4.394076
4,XAI_005,Positif,Positif,0.998155,High Confidence,membantu,membantu,NaN,1.760825,5.274494

✅ Summary Local SHAP berhasil dimuat.

## 1.6  Load Representative Detail

In [ ]:
# =====================================================
# CELL 6 : LOAD REPRESENTATIVE DETAIL
# =====================================================

print_header("LOAD REPRESENTATIVE DETAIL")

REPRESENTATIVE_FILE = os.path.join(
    PATHS["XE"],
    "Summary",
    "Representative_Sample.csv"
)

representative_df = pd.read_csv(
    REPRESENTATIVE_FILE
)

print()

print_info(
    f"Jumlah Representative : {len(representative_df)}"
)

display(
    representative_df.head()
)

print()

print_success(
    "Representative Detail berhasil dimuat."
)

============================================================
LOAD REPRESENTATIVE DETAIL
============================================================


ℹ️ Jumlah Representative : 6

,analysis_order,sample_id,text,actual_label,actual_sentiment,predicted_label,predicted_sentiment,prob_negatif,prob_netral,prob_positif,confidence,correct,prediction_case,confidence_level,selection_reason,sample_group,explain_status,analysis_group,detail_group
0,1,XAI_001,sangat membantu dan mudah,2,Positif,2,Positif,0.000885,0.000943,0.998172,0.998172,True,Benar_Positif,Tinggi,Prediksi benar kelas Positif,High Confidence,Pending,High Confidence,Positif
1,11,XAI_011,kenapa pas butuh banget di kasih driver rada j...,1,Netral,1,Netral,0.075137,0.784807,0.140055,0.784807,True,Benar_Netral,Sedang,Prediksi benar kelas Netral,High Confidence,Pending,High Confidence,Netral
2,6,XAI_006,buruk,0,Negatif,0,Negatif,0.991859,0.004897,0.003244,0.991859,True,Benar_Negatif,Tinggi,Prediksi benar kelas Negatif,High Confidence,Pending,High Confidence,Negatif
3,26,XAI_026,pembayaran gojek wajib 100 pakai gopay donk ja...,2,Positif,2,Positif,0.322563,0.292172,0.385265,0.385265,True,Benar_Confidence_Rendah,Rendah,Prediksi benar dengan confidence rendah,Low Confidence,Pending,Low Confidence,Low Confidence
4,16,XAI_016,oke,1,Netral,2,Positif,0.000980,0.000948,0.998072,0.998072,False,Salah_Netral_ke_Positif,Tinggi,Prediksi salah: Netral menjadi Positif,Error Analysis,Pending,Error Analysis,Netral menjadi Positif

✅ Representative Detail berhasil dimuat.

# BAB 2 Analisis High Confidence

Bab ini menyajikan analisis terhadap sampel pada kategori **High Confidence**, yaitu sampel yang diprediksi dengan tingkat keyakinan tinggi oleh model IndoBERT. Setiap kategori sentimen terdiri atas lima sampel yang diurutkan berdasarkan nilai confidence tertinggi. Analisis dilakukan dengan menampilkan ringkasan karakteristik SHAP, metadata prediksi, teks ulasan, serta observasi terhadap setiap kelompok sampel.

## 2.1 High Confidence Positif

In [ ]:
# =====================================================
# CELL 7 : LOAD HIGH CONFIDENCE POSITIVE
# =====================================================

print_header("LOAD HIGH CONFIDENCE POSITIVE")

high_positive = representative_df[
    (representative_df["analysis_group"] == "High Confidence") &
    (representative_df["detail_group"] == "Positif")
].reset_index(drop=True)

print()

print_info(
    f"Jumlah Sampel : {len(high_positive)}"
)

display(
    high_positive[
        [
            "sample_id",
            "actual_sentiment",
            "predicted_sentiment",
            "confidence"
        ]
    ]
)

print()

print_success(
    "High Confidence Positif berhasil dimuat."
)

============================================================
LOAD HIGH CONFIDENCE POSITIVE
============================================================


ℹ️ Jumlah Sampel : 1

  sample_id actual_sentiment predicted_sentiment  confidence
0   XAI_001          Positif             Positif    0.998172

✅ High Confidence Positif berhasil dimuat.

In [ ]:
# =====================================================
# CELL 8 : BUILD HIGH CONFIDENCE POSITIVE
# =====================================================

print_header("BUILD HIGH CONFIDENCE POSITIVE")

hc_positive = representative_df[
    (representative_df["analysis_group"] == "High Confidence") &
    (representative_df["detail_group"] == "Positif")
].copy()

hc_positive = hc_positive.sort_values(
    by="confidence",
    ascending=False
).reset_index(drop=True)

print()

print_info(
    f"Jumlah Sampel : {len(hc_positive)}"
)

display(
    hc_positive[
        [
            "sample_id",
            "actual_sentiment",
            "predicted_sentiment",
            "confidence"
        ]
    ]
)

print()

print_success(
    "High Confidence Positif berhasil dipersiapkan."
)

============================================================
BUILD HIGH CONFIDENCE POSITIVE
============================================================


ℹ️ Jumlah Sampel : 1

  sample_id actual_sentiment predicted_sentiment  confidence
0   XAI_001          Positif             Positif    0.998172

✅ High Confidence Positif berhasil dipersiapkan.

### Ringkasan High Confidence Positif

In [ ]:
# =====================================================
# CELL 9 : SUMMARY HIGH CONFIDENCE POSITIVE
# =====================================================

print_header("SUMMARY HIGH CONFIDENCE POSITIVE")

summary_positive = hc_positive.merge(

    summary_df,

    on="sample_id",

    how="left",

    suffixes=("", "_shap")

)

summary_positive = summary_positive[

    [

        "sample_id",

        "confidence",

        "top_token",

        "top_positive_token",

        "top_negative_token",

        "mean_abs_shap",

        "max_abs_shap",

        "text"

    ]

]

display(summary_positive)

print()

print_success(

    "Ringkasan High Confidence Positif berhasil dibuat."

)

============================================================
SUMMARY HIGH CONFIDENCE POSITIVE
============================================================

,sample_id,confidence,top_token,top_positive_token,top_negative_token,mean_abs_shap,max_abs_shap,text
0,XAI_001,0.998172,mudah,mudah,NaN,2.366605,3.954137,sangat membantu dan mudah

✅ Ringkasan High Confidence Positif berhasil dibuat.

### Statistik High Confidence Positif

In [ ]:
# =====================================================
# CELL 10 : STATISTIC HIGH CONFIDENCE POSITIVE
# =====================================================

print_header("STATISTIC HIGH CONFIDENCE POSITIVE")

print()

print_info(
    f"Jumlah Sampel            : {len(summary_positive)}"
)

print_info(
    f"Confidence Maksimum      : {summary_positive['confidence'].max():.6f}"
)

print_info(
    f"Confidence Minimum       : {summary_positive['confidence'].min():.6f}"
)

print_info(
    f"Rata-rata Confidence     : {summary_positive['confidence'].mean():.6f}"
)

print_info(
    f"Rata-rata Mean |SHAP|    : {summary_positive['mean_abs_shap'].mean():.6f}"
)

print_info(
    f"Rata-rata Max |SHAP|     : {summary_positive['max_abs_shap'].mean():.6f}"
)

print()

top_token = (

    summary_positive["top_token"]

    .value_counts()

    .idxmax()

)

print_info(
    f"Top Token Dominan        : {top_token}"
)

print()

print_success(
    "Statistik berhasil dihitung."
)

============================================================
STATISTIC HIGH CONFIDENCE POSITIVE
============================================================


ℹ️ Jumlah Sampel            : 1
ℹ️ Confidence Maksimum      : 0.998172
ℹ️ Confidence Minimum       : 0.998172
ℹ️ Rata-rata Confidence     : 0.998172
ℹ️ Rata-rata Mean |SHAP|    : 2.366605
ℹ️ Rata-rata Max |SHAP|     : 3.954137

ℹ️ Top Token Dominan        : mudah


✅ Statistik berhasil dihitung.

### Lima Ulasan High Confidence Positif

In [ ]:
# =====================================================
# CELL 11 : HIGH CONFIDENCE POSITIVE DETAIL
# =====================================================

print_header("HIGH CONFIDENCE POSITIVE DETAIL")

hc_positive_detail = representative_df[
    (representative_df["analysis_group"] == "High Confidence") &
    (representative_df["detail_group"] == "Positif")
].copy()

hc_positive_detail = hc_positive_detail.sort_values(
    by="confidence",
    ascending=False
).reset_index(drop=True)

print()

print_info(
    f"Jumlah Sampel : {len(hc_positive_detail)}"
)

display(hc_positive_detail)

print()

print_success(
    "Detail High Confidence Positif berhasil dimuat."
)

============================================================
HIGH CONFIDENCE POSITIVE DETAIL
============================================================


ℹ️ Jumlah Sampel : 1

,analysis_order,sample_id,text,actual_label,actual_sentiment,predicted_label,predicted_sentiment,prob_negatif,prob_netral,prob_positif,confidence,correct,prediction_case,confidence_level,selection_reason,sample_group,explain_status,analysis_group,detail_group
0,1,XAI_001,sangat membantu dan mudah,2,Positif,2,Positif,0.000885,0.000943,0.998172,0.998172,True,Benar_Positif,Tinggi,Prediksi benar kelas Positif,High Confidence,Pending,High Confidence,Positif

✅ Detail High Confidence Positif berhasil dimuat.